### ISSUE TITLE
Impossible to read labels of the comments form

### ISSUE THREAD

**Issue by mgsolipa** [b2evolution/pinit_skin#2]
![welcome_to_your_b2evolution-powered_website_](https://cloud.githubusercontent.com/assets/2645963/10499651/13d9533e-72d2-11e5-872e-cd0e8e568d42.png)

**Comment by miloszivojinovic** [comment]
I fixed this in the latest commit. 
Thanks for pointing this out.

**Comment by mgsolipa** [comment]
Thanks Milos.

I just added a new version number to your changes (1.2.2), in order to update the skins site (http://skins.b2evolution.net/pinit-skin) with a version different than the one I uploaded yesterday (1.2.1).
